cupom/urls.py
from django.urls import path
from . import views

app_name = 'cupom'

urlpatterns = [
    path('cupom/', views.AssimilaCupom.as_view(), name='cupom'),
    path('removercupom/', views.RemoverCupom.as_view(), name='removercupom'),
]

loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

DEBUG = True

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('cupom/', include('cupom.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.PagarPedido.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/<int:pk>', views.DetalhesPedido.as_view(), name='detalhespedido'),
    path('lista/', views.Lista.as_view(), name='lista'),

]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca'),
]

produto/models.py
from django.conf import settings
import os
from PIL import Image
from django.db import models
from django.utils.text import slugify
from uteis import utils


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(
        default=0, verbose_name='Preço Promo.')
    estoque = models.PositiveIntegerField(blank=True, null=True, default=1)
    profundidade = models.FloatField(verbose_name='Profundidade (cm)')
    largura = models.FloatField(verbose_name='Largura (cm)')
    altura = models.FloatField(verbose_name='Altura (cm)')
    peso = models.FloatField(verbose_name='Peso (kg)')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variável'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return utils.formata_preco(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promocional_formatado(self):
        return utils.formata_preco(self.preco_marketing_promocional)
    get_preco_promocional_formatado.short_description = 'Preço Promo.'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

produto/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q
from uteis import utils

from . import models
from perfil.models import Perfil
import requests

# Create your views here.

class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 5
    ordering = ['-id']

class Busca(ListaProdutos):
    def get_queryset(self, *args, **kwargs):
        termo = self.request.GET.get("termo") or self.request.session['termo']
        qs = super().get_queryset(*args, **kwargs)

        if not termo:
            return qs
        
        self.request.session['termo'] = termo

        qs = qs.filter(
            Q(nome__icontains=termo) |
            Q(descricao_curta__icontains=termo) |
            Q(descricao_longa__icontains=termo)
        )

        self.request.session.save()
        return qs

class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        '''if self.request.session.get('carrinho'):
            del self.request.session['carrinho']
            self.request.session.save()'''

        http_referer = self.request.META.get('HTTP_REFERER', reverse('produto:lista'))
        variacao_id = self.request.GET.get('vid')
        produto_id = self.request.GET.get('vid2')
        
        

        if produto_id:

            produto = get_object_or_404(models.Produto, id=produto_id)
            produto_nome = produto.nome
            preco_unitario = produto.preco_marketing
            preco_unitario_promocional = produto.preco_marketing_promocional
            quantidade = 1
            slug = produto.slug
            imagem = produto.imagem
            if imagem:
                imagem = imagem.name
            else:
                imagem=''

            if produto.estoque < 1:
                messages.error(self.request, 'Estoque insuficiente')
                return redirect(http_referer)

            if not self.request.session.get('carrinho'):
                self.request.session['carrinho'] = {}
                self.request.session.save()

            carrinho = self.request.session['carrinho']

            

            if produto_id in list(carrinho.keys()):
                quantidade_carrinho = carrinho[produto_id]['quantidade']
                quantidade_carrinho += 1

                if produto.estoque < quantidade_carrinho:
                    messages.warning(self.request, f'Estoque insuficiente, temos apenas {produto.estoque} unidades de {produto_nome}')
                    return redirect(f'/{slug}')


                carrinho[produto_id]['quantidade'] = quantidade_carrinho
                carrinho[produto_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
                carrinho[produto_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho


            else:
                carrinho[produto_id] = {
                    'produto_id' : produto_id,
                    'produto_nome' : produto_nome,
                    'preco_unitario' : preco_unitario,
                    'preco_unitario_promocional' : preco_unitario_promocional,
                    'preco_quantitativo' : preco_unitario,
                    'preco_quantitativo_promocional' : preco_unitario_promocional,
                    'quantidade' : 1,
                    'slug' : slug,
                    'altura' : produto.altura,
                    'peso' : produto.peso,
                    'profundidade' : produto.profundidade,
                    'largura' : produto.largura,
                    'imagem' : imagem,
                }                
            self.request.session.save()

            messages.success(self.request, f'Produto {produto_nome} adicionado ao seu carrinho')
            return redirect(http_referer)


        if variacao_id == None:
            print('printei2')
            messages.error(self.request, 'Escolha uma opção')
            return redirect(http_referer)

        if not variacao_id:
            messages.error(self.request, 'Produto não existe')
            return redirect(http_referer)


        
        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        variacao_id = f'1-{variacao_id}'
        variacao_estoque = variacao.estoque
        produto = variacao.produto

        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem
        if imagem:
            imagem = imagem.name
        else:
            imagem=''

        if variacao.estoque < 1:
            messages.error(self.request, 'Estoque insuficiente')
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.warning(self.request, f'Estoque insuficiente, temos apenas {variacao_estoque} unidades de {produto_nome} {variacao_nome}')
                return redirect(f'/{slug}')


            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho


        else:
            carrinho[variacao_id] = {
                'produto_id' : produto_id,
                'produto_nome' : produto_nome,
                'variacao_nome' : variacao_nome,
                'variacao_id' : variacao_id,
                'preco_unitario' : preco_unitario,
                'preco_unitario_promocional' : preco_unitario_promocional,
                'preco_quantitativo' : preco_unitario,
                'preco_quantitativo_promocional' : preco_unitario_promocional,
                'quantidade' : 1,
                'slug' : slug,
                'altura' : produto.altura,
                'peso' : produto.peso,
                'profundidade' : produto.profundidade,
                'largura' : produto.largura,
                'imagem' : imagem,
            }
        self.request.session.save()
        messages.success(self.request, f'Produto {produto_nome} {variacao_nome} adicionado ao seu carrinho')
        return redirect(http_referer)


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFER', reverse('produto:lista'))
        variacao_id = self.request.GET.get('vid')
        produto_id = self.request.GET.get('vid2')
        frete = self.request.session.get('frete')

        if not variacao_id and not produto_id:
            return redirect(http_referer)
        
        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho'] and produto_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        if variacao_id:
            carrinho = self.request.session['carrinho'][variacao_id]
            
            context = {
            'carrinho': self.request.session.get('carrinho', {}),
            'frete': frete
            }

            messages.success(self.request, f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} removido ao seu carrinho')
            del self.request.session['carrinho'][variacao_id]
            self.request.session.save()
            return render(self.request, 'produto/carrinho.html', context)
        else:
            carrinho = self.request.session['carrinho'][produto_id]

            context = {
            'carrinho': self.request.session.get('carrinho', {}),
            'frete': frete
            }

            del self.request.session['carrinho'][produto_id]
            self.request.session.save()

            if not self.request.session.get('carrinho'):
                messages.error(
                    self.request,
                    'Carrinho vazio.'
                )
                return redirect('produto:lista')

            messages.success(self.request, f'Produto {carrinho["produto_nome"]} removido ao seu carrinho')
            return render(self.request, 'produto/carrinho.html', context)
        

class Carrinho(View):
    def get(self, *args, **kwargs):
        
        # pego perfil para pegar o cep
        # implemento API
        # passo para o contexto os valores da API
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Cadastre-se antes de acessar o seu carrinho')
            return redirect('perfil:criar')

        perfil = get_object_or_404(Perfil.objects.filter(usuario=self.request.user))
    
        url = "https://www.melhorenvio.com.br/api/v2/me/shipment/calculate"

        payload = {
            "from": { "postal_code": f"{perfil.cep}" },
            "to": { "postal_code": "90570020" },
            "package": {
                "height": 4,
                "width": 12,
                "length": 17,
                "weight": 1
            }
        }
        headers = {

produto/templates/produto/carrinho.html
{% extends "base.html" %}
{% load omfilters %}

{% block titulo %}Carrinho |{% endblock titulo %}

{% block conteudo %}

{% if carrinho %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            {% include "parciais/_carrinho.html" %}
        </div>
    </div>



    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{carrinho|cart_totals|formata_preco}} + {{frete|formata_preco}} (Frete) = {{carrinho|cart_totals_mais_frete:frete}}</td>
                    </tr>
                    <tr>
                        <td> </td>
                        {% if cupom %}<td style='color:darkgreen'>{{carrinho|cart_totals_mais_frete:frete}} -{{desconto}}% = {{total_com_desconto|formata_preco}}</td>{% endif %}
                    </tr>
                    <tr>
                        <td class="font-weight-bold">Cupom de desconto</td>
                        <td>
                            <form method="get" action="{% url 'cupom:cupom' %}">
                                <input type="text" name="cupom" id="cupom">
                                <button type="submit">Aplicar cupom</button>
                                {% if cupom %}<span>Aplicado cupom {{cupom}}</span>
                                <a class="ml-3" href="{% url "cupom:removercupom" %}">
                                <i class="fa-times-circle text-danger" aria-hidden="true">remover</i>{% endif %}
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            <a class="btn btn-lg btn-block btn-primary" href="{% url "produto:resumodacompra" %}">
                Finalizar a compra
            </a>
        </div>
    </div>

{% else %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Seu carrinho está vazio.</p>
        <a class="btn btn-lg btn-block btn-primary" href="{% url "produto:lista" %}">
            Voltar apara a loja
        </a>
    </div>
</div>

{% endif %}

{% endblock conteudo %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}

{% block titulo %}{{ produto.nome }} | {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if produto.imagem %}
                <img class="img-fluid" src="{{ produto.imagem.url }}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{ produto.nome }}</h1>
            <p class="lead">{{ produto.descricao_curta }}</p>
            <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                <div class="form-group">
                    {% if produto.variacao_set.all %}
                        <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                            <option value="" disabled selected>Escolha uma opção</option>
                            
                            {% for variacao in produto.variacao_set.all %}

                            {% if variacao.preco_promocional %}
                            <option data-preco="{{ variacao.preco|formata_preco }}"
                                data-preco-promocional="{{ variacao.preco_promocional|formata_preco }}"
                                value="{{ variacao.id }}">
                                {% if variacao.nome %}
                                {{ variacao.nome }}
                                {% else %}
                                {{ variacao }}
                                {% endif %}
                            </option>
                            {% else %}
                            <option data-preco="{{ variacao.preco|formata_preco }}" value="{{ variacao.id }}">
                                {% if variacao.nome %}
                                {{ variacao.nome }}
                                {% else %}
                                {{ variacao }}
                                {% endif %}
                            </option>
                            {% endif %}

                            {% endfor %}
                        </select>
                    {% else %}
                    <select id="select-variacoes" name="vid2" class="form-control form-control-lg">
                        <option value="{{produto.id}}">Sem variações</option>
                    </select>
                    {% endif %}
                </div>


                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Adicionar ao carrinho
                    </button>
                </div>

            </form>

            <p class="lead">
                {% if not produto.variacao_set.all %}
                    {% if produto.preco_marketing_promocional %}
                        <span id="variation-preco-promocional" class="lead product-price">
                            {{ produto.preco_marketing_promocional|formata_preco }}
                        </span>
                        <span id="variation-preco" class="lead product-old-price text-muted">
                            {{ produto.preco_marketing|formata_preco }}
                        </span>
                    {% else %}
                        <span id="variation-preco" class="lead product-price">
                            {{ produto.preco_marketing|formata_preco }}
                        </span>
                    {% endif %}
                {% else %}
                    <span id="variation-preco-promocional" class="lead product-price preco-com-promo" style='display: none;'>
                        {{ produto.preco_marketing_promocional|formata_preco }}
                    </span>
                    <span id="variation-preco" class="lead product-price preco-sem-promo" style='display: none;'>
                        {{ produto.preco_marketing|formata_preco }}
                    </span>
                    <span id="variation-preco" class="lead product-old-price text-muted" style='display: none;'>
                        {{ produto.preco_marketing|formata_preco }}
                    </span>
                {% endif %}
            </p>

            <script>
                (function () {
                    
                    select_variacao = document.getElementById('select-variacoes');
                    variation_preco = document.getElementById('variation-preco');
                    variation_preco_promocional = document.getElementById('variation-preco-promocional');
                
                    if (!select_variacao) {
                        console.log("Esta função foi executada imediatamente !select_variacao!");
                        return;
                    }
                
                    if (!variation_preco) {
                        console.log("Esta função foi executada imediatamente !variation_preco!");
                        
                    }
                    
                    select_variacao.addEventListener('change', function () {
                        preco = this.options[this.selectedIndex].getAttribute('data-preco');
                        preco_promocional = this.options[this.selectedIndex].getAttribute('data-preco-promocional');
                        variation_preco.innerHTML = preco;

                        if (!preco_promocional) {
                            spanPrecoComPromo = document.getElementsByClassName('preco-com-promo')[0];
                            spanPrecoMutado = document.getElementsByClassName('text-muted')[0];
                            spanPrecoComPromo.style.display = 'none';
                            spanPrecoMutado.style.display = 'none';
                            spanPrecoSemPromo = document.getElementsByClassName('preco-sem-promo')[0];
                            spanPrecoSemPromo.classList.remove('product-old-price');
                            spanPrecoSemPromo.style.display = 'block';
                            console.log("nao variou preço promo!");
                        }
                        
                        else {
                            spanPrecoComPromo = document.getElementsByClassName('preco-com-promo')[0];
                            spanPrecoMutado = document.getElementsByClassName('text-muted')[0];
                            spanPrecoComPromo.style.display = 'block';
                            spanPrecoMutado.style.display = 'none';
                            spanPrecoSemPromo = document.getElementsByClassName('preco-sem-promo')[0];
                            spanPrecoSemPromo.classList.add('product-old-price');
                            spanPrecoSemPromo.style.display = 'block';
                            variation_preco_promocional.innerHTML = preco_promocional;                
                            console.log("variou preço promo!");
                        }
                    })
                    
                    
                })();
                
            </script>



        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ produto.nome }}</h2>
            {{ produto.descricao_longa|linebreaks }}
        </div>
    </div>
</div>


{% endblock %}

produto/templates/produto/lista.html
{% extends "base.html" %}
{% load omfilters %}

{% block titulo %}E-commerce{% endblock titulo %}

{% block conteudo %}

<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}
                <div class="card">
                    {% if produto.imagem %}
                    <a href="{% url "produto:detalhe" produto.slug %}">
                        <img class="card-img-top" src="{{produto.imagem.url}}" alt="{{produto.nome}}">
                    </a>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{produto.nome}}</h5>
                        <p class="card-text">{{produto.descricao_curta}}</p>
                        <div class="container product-price-block text-center">
                            {% if produto.preco_marketing_promocional %}
                            <span class="product-price">
                                {{produto.preco_marketing_promocional|formata_preco}}
                            </span>
                            <span class="product-old-price text-muted">
                                {{produto.preco_marketing|formata_preco}}
                            </span>
                            {% else %}
                            <span class="product-price">
                                {{produto.preco_marketing|formata_preco}}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top-light-custom text-center">
                        <a href={% url "produto:detalhe" produto.slug %} class="btn btn-primary btn-sm m-1 btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Comprar
                        </a>
                    </div>
                </div>
            {% endfor %}





        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include "parciais/_pagination.html" %}
    </div>
</div>

{% endblock conteudo %}

produto/templates/produto/resumodacompra.html
{% extends "base.html" %}
{% load omfilters %}

{% block titulo %}Resumo da compra |{% endblock titulo %}

{% block conteudo %}
<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url "perfil:criar" %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{usuario.first_name}}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{usuario.last_name}}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{usuario.perfil.idade}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{usuario.perfil.data_nascimento}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{usuario.perfil.cpf}}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{usuario.email}}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url "perfil:criar" %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{usuario.perfil.endereco}}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{usuario.perfil.numero}}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{usuario.perfil.complemento}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{usuario.perfil.bairro}}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{usuario.perfil.cidade}}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{usuario.perfil.estado}}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{usuario.perfil.cep}}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include "parciais/_carrinho.html" %}
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url "pedido:salvarpedido" %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>

{% endblock conteudo %}